# Generated by Django 3.2 on 2021-05-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0001_squashed_0002_auto_20210505_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='spare',
            field=models.ManyToManyField(blank=True, to='bboard.Spare', verbose_name='Выбрать засную машину'),
        ),
    ]
