# Generated by Django 3.2 on 2021-05-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bb',
            options={'get_latest_by': 'published', 'ordering': ['-published'], 'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
        migrations.AlterField(
            model_name='bb',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Титул.'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='name',
            field=models.CharField(blank=True, help_text='Напишите модель авто и объем мотора и тип топлива', max_length=100, null=True, verbose_name='Машина'),
        ),
        migrations.AlterUniqueTogether(
            name='bb',
            unique_together={('title', 'price', 'rubric', 'kind'), ('title', 'price', 'published', 'kind')},
        ),
    ]
