# Generated by Django 3.2 on 2021-05-14 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0002_alter_machine_spare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='image',
            field=models.ImageField(upload_to='bboard/%Y/%M/%D'),
        ),
    ]
