# Generated by Django 3.2 on 2021-05-05 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0004_auto_20210504_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='bb',
            name='help_texts',
            field=models.TextField(default=1, help_text='□ help text— дополнительный поясняющий текст, выводимый на экран. По\nумолчанию — пустая строка.\nСодержащиеся в этом тексте специальные символы HTML не преобразуются\nв литералы и выводятся как есть. Это позволяет отформатировать поясняющий\nтекст HTML-тегами;'),
            preserve_default=False,
        ),
    ]
