# Generated by Django 3.2 on 2021-05-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0005_bb_help_texts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bb',
            name='help_texts',
        ),
        migrations.AddField(
            model_name='bb',
            name='kind',
            field=models.CharField(choices=[('b', 'Куплю'), ('s', 'Продам'), ('c', 'Обменяю'), ('r', 'Аренда')], default='s', max_length=1, verbose_name='Тип объявления'),
        ),
    ]
