# Generated by Django 3.2 on 2021-05-05 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0007_advuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='запаная машина')),
            ],
            options={
                'verbose_name': 'Добавить запасную.',
                'verbose_name_plural': 'Добавить запасные.',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='vашина')),
                ('spare', models.ManyToManyField(to='bboard.Spare', verbose_name='Выбрать засную машину')),
            ],
            options={
                'verbose_name': 'Добавить машину.',
                'verbose_name_plural': 'Добавить машины.',
                'ordering': ['name'],
            },
        ),
    ]
