# Generated by Django 3.2 on 2021-04-22 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название новости')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Контент новости')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Последнее изменения')),
                ('photo', models.ImageField(upload_to='photos/%Y/%M/%D', verbose_name='Загрузка картинки')),
                ('is_published', models.BooleanField(help_text='Выбор публикации', verbose_name='Публикация')),
            ],
        ),
    ]
