# Generated by Django 3.2 on 2021-04-25 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salutation', models.CharField(max_length=30, verbose_name='Приведствие')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО Автора')),
                ('email', models.EmailField(max_length=254, verbose_name='Е-Почта')),
                ('headshot', models.ImageField(upload_to='author_image')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название Издателя')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес Издателя')),
                ('city', models.CharField(max_length=60, verbose_name='Город Издателя')),
                ('state_province', models.CharField(max_length=60, verbose_name='Провинция Издателя')),
                ('country', models.CharField(max_length=60, verbose_name='Страна Издателя')),
                ('website', models.URLField()),
            ],
            options={
                'verbose_name': 'Издателя',
                'verbose_name_plural': 'Издатели',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название книги')),
                ('publication_date', models.DateField(auto_now=True)),
                ('authors', models.ManyToManyField(to='Views.Author', verbose_name='Авторы книги')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Views.publisher')),
            ],
            options={
                'verbose_name': 'Книгу',
                'verbose_name_plural': 'Книги',
                'ordering': ['publication_date'],
            },
        ),
    ]
