# Generated by Django 3.2 on 2021-04-21 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя Автора')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, verbose_name='Категория блога')),
                ('tag_line', models.TextField()),
            ],
            options={
                'verbose_name': 'Категория блога',
                'verbose_name_plural': 'Категории блогов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(blank=True, max_length=250, null=True, verbose_name='подзаголовок')),
                ('body_text', models.TextField()),
                ('pub_date', models.DateField(auto_now=True)),
                ('mod_date', models.DateField(auto_now_add=True)),
                ('number_of_comments', models.IntegerField()),
                ('number_of_pingbacks', models.IntegerField()),
                ('rating', models.PositiveSmallIntegerField()),
                ('authors', models.ManyToManyField(to='job.Author', verbose_name='Авторы')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.blog')),
            ],
            options={
                'verbose_name': 'Блог',
                'verbose_name_plural': 'Блоги',
                'ordering': ['-headline'],
            },
        ),
    ]
