# Generated by Django 3.2 on 2021-04-24 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_author_blog_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя группы.')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_join', models.DateTimeField(auto_now=True)),
                ('invite_reason', models.CharField(max_length=70)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.group')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.person')),
            ],
            options={
                'verbose_name': 'Членство',
                'verbose_name_plural': 'Члены группы',
                'ordering': ['group'],
            },
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(through='job.Membership', to='job.Person'),
        ),
    ]
